---
# Define Vault configuration which is converted to JSON using template
# https://www.vaultproject.io/docs/configuration
hashi_vault_configuration:
  api_addr: "{{ 'http://'+hostvars[inventory_hostname]['ansible_'+vault_bind_interface]['ipv4']['address']+':8200' }}"
  listener:
    # First address will always be used to define url
    - tcp:
        address: 127.0.0.1:8200
        cluster_address: 127.0.0.1:8201
        tls_disable: true
  storage:
    file:
      path: /var/lib/vault
  ui: true

hashi_vault_master: "{{ inventory_hostname }}"
