---
- hosts: all
  tasks:
    - name: Applying ansible-bootstrap-python role
      import_role:
        name: ansible-bootstrap-python

- import_playbook: consul.yml

- import_playbook: vault.yml

- import_playbook: loadbalancers.yml

- import_playbook: app_servers.yml
